# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(305, 600)
        self.checkBox_6 = QtWidgets.QCheckBox(Widget)
        self.checkBox_6.setGeometry(QtCore.QRect(30, 40, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")


        # choose button
        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(64, 270, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")


        # clear button
        self.pushButton_2 = QtWidgets.QPushButton(Widget)
        self.pushButton_2.setGeometry(QtCore.QRect(62, 325, 175, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton")

        # send button
        self.pushButton_1 = QtWidgets.QPushButton(Widget)
        self.pushButton_1.setGeometry(QtCore.QRect(70, 360, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton")

        # title
        self.label_8 = QtWidgets.QLabel(Widget)
        self.label_8.setGeometry(QtCore.QRect(57, 3, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        # commands label
        self.label_9 = QtWidgets.QLabel(Widget)
        self.label_9.setGeometry(QtCore.QRect(50, 415, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_8")

        # line
        self.line_4 = QtWidgets.QFrame(Widget)
        self.line_4.setGeometry(QtCore.QRect(0, 28, 1581, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")





        self.checkBox_7 = QtWidgets.QCheckBox(Widget)
        self.checkBox_7.setGeometry(QtCore.QRect(30, 60, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Widget)
        self.checkBox_8.setGeometry(QtCore.QRect(30, 80, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(Widget)
        self.checkBox_9.setGeometry(QtCore.QRect(30, 100, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")

        self.checkBox_1 = QtWidgets.QCheckBox(Widget)
        self.checkBox_1.setGeometry(QtCore.QRect(30, 120, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setObjectName("checkBox_1")

        self.checkBox_2 = QtWidgets.QCheckBox(Widget)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 140, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_1")

        self.checkBox_3 = QtWidgets.QCheckBox(Widget)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 160, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_1")

        self.checkBox_4 = QtWidgets.QCheckBox(Widget)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 180, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_1")

        self.checkBox_5 = QtWidgets.QCheckBox(Widget)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 200, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_1")

        self.checkBox_10 = QtWidgets.QCheckBox(Widget)
        self.checkBox_10.setGeometry(QtCore.QRect(30, 220, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_1")

        self.checkBox_11 = QtWidgets.QCheckBox(Widget)
        self.checkBox_11.setGeometry(QtCore.QRect(30, 240, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_1")


        self.text = QtWidgets.QTextBrowser(Widget)
        self.text.setGeometry(QtCore.QRect(50, 445, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text.setFont(font)
        self.text.setObjectName("label")

        # self.text=QtWidgets.QTextBrowser(Widget)

        self.label = QtWidgets.QLabel("Test", Widget)
        self.label.setGeometry(QtCore.QRect(125, 555, 53, 30))
        self.label.setStyleSheet("background:rgb(255,50,50)")
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)




        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

        self.label.hide()


        self.pushButton.clicked.connect(lambda: self.checked())
        self.pushButton_1.clicked.connect(lambda: self.send())
        self.pushButton_2.clicked.connect(lambda: self.clear())


        self.s = ""

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.checkBox_6.setText(_translate("Widget", "openCom"))
        self.checkBox_7.setText(_translate("Widget", "closeCom"))
        self.checkBox_8.setText(_translate("Widget", "openADCS"))
        self.checkBox_9.setText(_translate("Widget", "closeADCS"))
        self.checkBox_1.setText(_translate("Widget", "openPayload"))
        self.checkBox_2.setText(_translate("Widget", "closePayload"))
        self.checkBox_3.setText(_translate("Widget", "getTLM"))
        self.checkBox_4.setText(_translate("Widget", "getStoredTLM"))
        self.checkBox_5.setText(_translate("Widget", "getImage"))
        self.checkBox_10.setText(_translate("Widget", "clearTLM"))
        self.checkBox_11.setText(_translate("Widget", "clearImgs"))

        self.pushButton.setText(_translate("Widget", "Choose commands"))
        self.pushButton_1.setText(_translate("Widget", "Send Commands"))
        self.pushButton_2.setText(_translate("Widget", "Clear Commands"))
        self.text.setText(_translate("Widget", ""))
        self.label_8.setText(_translate("Widget", "Satellite Control"))
        self.label_9.setText(_translate("Widget", "Commands:"))
        self.label.setText(_translate("Widget", "ACK"))


    def checked(self):
        l="openCom,closeCom,openADCS,closeADCS,openPayload,closePayload,getTLM,getStoredTLM,getImage,clearTLM,clearImgs".split(",")

        if self.checkBox_6.isChecked():
            self.s+=l[0]+"\n"
        elif self.checkBox_7.isChecked():
            self.s += l[1] + "\n"
        elif self.checkBox_8.isChecked():
            self.s += l[2] + "\n"
        elif self.checkBox_9.isChecked():
            self.s += l[3] + "\n"

        elif self.checkBox_1.isChecked():
            self.s += l[4] + "\n"
        elif self.checkBox_2.isChecked():
            self.s += l[5] + "\n"
        elif self.checkBox_3.isChecked():
            self.s += l[6] + "\n"
        elif self.checkBox_4.isChecked():
            self.s += l[7] + "\n"
        elif self.checkBox_5.isChecked():
            self.s += l[8] + "\n"
        elif self.checkBox_10.isChecked():
            self.s += l[9] + "\n"
        elif self.checkBox_11.isChecked():
            self.s += l[10] + "\n"
        self.text.setText(self.s)
        # print(self.checkBox_6.())
        for i in range(1,12):
            exec("self.checkBox_{}.setChecked(False)".format(i))

    def clear(self):
        self.s=""
        self.text.setText(self.s)

        for i in range(1,12):
            exec("self.checkBox_{}.setChecked(False)".format(i))



    def send(self):
        # put here the sending function                     ###########



        l=self.s.split("\n")[:-1]

        for i in range(len(l)):
            if True:            # change this condition to whatever u want
                l[i]=l[i].ljust(15)+"--> OK"
        self.s="\n".join(l)
        self.text.setText(self.s)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
